services:
  mysql_db_container:
    image: mysql:latest
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "chat-app"
      MYSQL_USER: "papcaii"
      MYSQL_PASSWORD: "123456"
    ports:
      - 3307:3306
  adminer:
    image: adminer
    environment:
        ADMINER_DEFAULT_SERVER: mysql_db_container
    restart: always
    ports:
      - 8081:8080
      
volumes:
  mysql-data:
